[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
subscription_program = "SubProg111111111111111111111111111111111111"
receipt_program = "Receipt111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/suzanrana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
